on:
  push:
    branches:
      - master
      - release/*
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || 'test' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set deployment variables
        id: vars
        run: |
          echo "ENVIRONMENT=${{ vars.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "STACK_NAME=${{ vars.STACK_NAME }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ vars.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ vars.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_DBNAME=${{ vars.DB_DBNAME }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
      - run: sam build --use-container
      - run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --parameter-overrides \
              CrudHost="${{ env.DB_HOST }}" \
              CrudPort="${{ env.DB_PORT }}" \
              CrudUsername="${{ env.DB_USERNAME }}" \
              CrudPass="${{ env.DB_PASSWORD }}" \
              CrudDB="${{ env.DB_DBNAME }}" \
            --capabilities CAPABILITY_IAM
